### PR TITLE
 fix: variable names and event handling logic 

### PR DESCRIPTION
**Pull request by intls**
## Why is this change needed?

Describe why this issue should be fixed and link to any relevant design docs, issues or other relevant items.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] PR has a [changeset](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#35-adding-changesets)
- [ ] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] PR includes [documentation](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#32-writing-docs) if necessary.

---

## PR-Codex overview
This PR focuses on correcting typos in function and variable names across multiple files, specifically related to "verifications" and "multi addresses". It also ensures consistent naming conventions throughout the codebase.

### Detailed summary
- Fixed typo: `solanaVerficationsEnabled` to `solanaVerificationsEnabled`.
- Corrected `getAllVerficationMessagesByFid` to `getAllVerificationMessagesByFid`.
- Changed `processRustCommitedTransaction` to `processRustCommittedTransaction`.
- Updated `ConnectToMutliAddr` to `ConnectToMultiAddr` in various locations.
- Ensured consistent naming in comments.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by intls** [comment]
@sds Hey! Resolved conflicts and opened a new PR.

**Comment by sds** [comment]
Looks like tests are failing.

**Comment by intls** [comment]
> Looks like tests are failing.

@sds How can I solve it?

**Comment by sds** [comment]
Look at the `packages/shuttle/src/shuttle.integration.test.ts` [change](https://github.com/farcasterxyz/hub-monorepo/pull/2421/files#diff-6c51706da1f29c269f8ca39dc743857cb5ec96e4c38f5e7c82fe3cf33b73ebe7R564). 

It appears that there are now two declarations of the same method (`getAllVerificationMessagesByFid`) in this file, based on the error.

**Pull request closed without merging**
