### PR TITLE
fix: changed USERNAME to FNAME for UserDataType

### PR DESCRIPTION
**Pull request by maxmandia**
## Motivation

The USERNAME enum value does not exists on UserDataType. Swapped it with FNAME. 

## Change Summary

USERNAME -> FNAME

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [ ] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] PR has a [changeset](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#35-adding-changesets)
- [ ] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [ ] PR does not require changes to the [protocol](https://github.com/farcasterxyz/protocol)
- [ ] All [commits have been signed](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#22-signing-commits)

## Additional Context

If this is a relatively large or complex change, provide more details here that will help reviewers

---

## PR-Codex overview

> The following files were skipped due to too many changes: `packages/hub-nodejs/examples/chron-feed/yarn.lock`, `packages/hub-nodejs/examples/chron-feed/package-lock.json`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by maxmandia** [comment]
To clarify how this PR came to be: 

I was reading the docs https://www.farcaster.xyz/developers/examples.html and wanted to run the chron example on my machine. Got an error because a bad ENUM value was present and quickly swapped it out for an appropriate default.

**Comment by maxmandia** [comment]
@varunsrin is it cool to commit lock files?

**Comment by deodad** [comment]
@maxmandia we recently [renamed the FNAME enum to USERNAME](https://github.com/farcasterxyz/hub-monorepo/commit/4fa7a5615315e4733626d82713ec067babd4efd4) since it can now represent either an FNAME or ENS name

We hadn't bumped the @farcaster/hub-nodejs version yet in that example repo but I fixed this yesterday with https://github.com/farcasterxyz/hub-monorepo/pull/1126

If you pull the latest you should be gtg

**Comment by maxmandia** [comment]
> 

Sounds good! Feel free to close this issue when you're ready.

**Pull request closed without merging**
