### PR TITLE
Add a tutorial for running Hubble on GCP

### PR DESCRIPTION
**Pull request by anovalunosis**
## Motivation

This PR adds a new tutorial to Hubble docs. The tutorial is about running Hubble on GCP.

## Change Summary

Adds a new tutorial to run a hubble on Google Cloud Platform.

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [ ] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [ ] PR has a [changeset](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#35-adding-changesets)
- [ ] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [x] PR includes [documentation](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#32-writing-docs) if necessary.
- [ ] All [commits have been signed](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#22-signing-commits)

---

## PR-Codex overview
The focus of this PR is to add a detailed guide for setting up Hubble on Google Cloud Platform (GCP) including creating a GCP VM, using Terraform, and running Hubble.

### Detailed summary
- Added a step-by-step guide for setting up Hubble on GCP
- Included requirements, costs, and detailed instructions
- Provided Terraform configuration for creating a GCP VM
- Added images for visual aid in the guide

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by anovalunosis** [comment]
Looking forward to your feedback happy NY :clinking_glasses: !

**Comment by anovalunosis** [comment]
@sanjayprabhu could you help me with merging this one? ☺️

**Comment by christopherwxyz** [comment]
@anovalunosis this is out of date, so you'll likely need to update it with minimum requirements.

**Comment by anovalunosis** [comment]
@christopherwxyz  minimum requirements updated like you requested.

**Comment by sds** [comment]
Thanks!

**Pull request merged**
