### PR TITLE
Fname register signature fix

### PR DESCRIPTION
**Pull request by prtk418**
## Why is this change needed?

There was a bug due to which fname registration was failing on example package `hello-world`. The PR fixes this.

---

## PR-Codex overview
This PR introduces a new function for creating user name proof claims and updates the way user name proof signatures are generated and processed in the `registerFname` function. It also adds a utility function for converting bytes to hex.

### Detailed summary
- Added `makeUserNameProofClaim` function import.
- Introduced `bytesToHex` function import.
- Updated `registerFname` to use `await signer.signUserNameProofClaim` with `makeUserNameProofClaim`.
- Changed signature processing to use `bytesToHex` for `userNameProofSignature.value`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by aditiharini** [comment]
How did you discover this error? Any chance you could provide the fid you were using for testing? We saw errors in our logs that seemingly line up with this issue you're reporting-- I want to further validate.

**Comment by prtk418** [comment]
> How did you discover this error? Any chance you could provide the fid you were using for testing? We saw errors in our logs that seemingly line up with this issue you're reporting-- I want to further validate.

I was registering a new fid using the same script along with fname - https://github.com/farcasterxyz/hub-monorepo/pull/2384/files#diff-718bf604324aedd7401075eee0a6e08762dc76bde40a11735b1fe0a1e4aebe9bR117

**Comment by prtk418** [comment]
@aditiharini is there a python equivalent for these packages? I know this is unrelated. However couldn't find a better channel to ask this.

**Comment by sds** [comment]
There are no Python packages that we maintain, and I'm not aware of any others at this time (but they might be out there!)

**Pull request merged**
