### PR TITLE
feat: ensure hub networks match when syncing with peers

### PR DESCRIPTION
**Pull request by sanjayprabhu**
## Motivation

Fixes: https://github.com/farcasterxyz/hub-monorepo/issues/835. Prevents testnet hubs from accidentally syncing mainnet and vice versa

## Change Summary

Check the peer hubs network and make sure it matches ours before syncing

## Merge Checklist

_Choose all relevant options below by adding an `x` now or at any time before submitting for review_

- [x] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [x] PR has a [changeset](../CONTRIBUTING.md#35-adding-changesets)
- [x] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [x] PR does not require changes to the [protocol](https://github.com/farcasterxyz/protocol)

## Additional Context

If this is a relatively large or complex change, provide more details here that will help reviewers

### CODE REVIEW

**Comment by adityapk00** [comment]
Shouldn't we set the network when gossiping out in `getContactInfoContent` ?

**Comment by sanjayprabhu** [comment]
Whoops, good point. Was in too much of a hurry.

**Comment by sanjayprabhu** [comment]
Also, there's too much logic in `hubble.ts`. We really need to make it more easily testable.

**Comment by adityapk00** [comment]
Looks good!

**Pull request merged**
