### PR TITLE
feat: support fallback RPC providers

### PR DESCRIPTION
**Pull request by stephancill**
CLI now supports comma separated RPC URLs to fall back on (--eth-rpc-url, --eth-mainnet-rpc-url, --l2-rpc-url)

## Motivation

"This ensures that if a backend has become out-of-sync, or if it has been compromised that its responses are dropped in favor of responses that match the majority." #742.

## Change Summary

Implements backwards-compatible fallback URLs using viem's `fallback` transport, as suggested by #742.
Makes use of existing --eth-rpc-url, --eth-mainnet-rpc-url, --l2-rpc-url arguments, but splits by ',' to support multiple URLs to fall back on if others are not responding.

## Merge Checklist

- [x] PR title adheres to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standard
- [x] PR has a [changeset](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#35-adding-changesets)
- [x] PR has been tagged with a change label(s) (i.e. documentation, feature, bugfix, or chore)
- [x] PR does not require changes to the [protocol](https://github.com/farcasterxyz/protocol)
- [x] All [commits have been signed](https://github.com/farcasterxyz/hub-monorepo/blob/main/CONTRIBUTING.md#22-signing-commits)

## Additional Context

Ranking can also be enabled. This would periodically make additional calls to each RPC URL every 10 seconds to determine its ranking based on [latency and stability](https://viem.sh/docs/clients/transports/fallback.html#transport-ranking). Perhaps this configuration could be exposed to the user via CLI?

---

## PR-Codex overview
This PR focuses on adding support for fallback RPC providers in the Hubble application. 

### Detailed summary
- Added `fallback` function to the `viem` library to handle fallback RPC providers.
- Modified `L2EventsProvider` and `EthEventsProvider` classes to support multiple RPC URLs.
- Updated the `Hub` class to use the `rankRpcs` option and fallback transports for RPC providers.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by deodad** [comment]
Thanks @stephancill!

**Comment by deodad** [comment]
> Ranking can also be enabled. This would periodically make additional calls to each RPC URL every 10 seconds to determine its ranking based on [latency and stability](https://viem.sh/docs/clients/transports/fallback.html#transport-ranking). Perhaps this configuration could be exposed to the user via CLI?

I'm supportive

**Comment by stephancill** [comment]
@deodad do you think there should be a single --rank-rpc option that applies to all RPCs or should there be one for each kind of RPC?

**Comment by deodad** [comment]
> @deodad do you think there should be a single --rank-rpc option that applies to all RPCs or should there be one for each kind of RPC?

Starting with a single option at the CLI level to turn on automatic ranking globally is good. A more sophisticated approach would allow a config file where users could do fine grained configuration of urls, ranking parameters per chains, but let's take the simple win first. Thank you!

**Comment by deodad** [comment]
This is awesome thank you!

**Pull request merged**
